name: CLA

on:
 push:
   branches: master
 pull_request:

jobs:
  CheckCLA:
    runs-on: ubuntu-latest
    name: Checks that all committers are in CONTRIBUTORS
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 0
      - name: Run Check
        run: ./ci/cla.sh
